language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
          packages:
            - g++-7
            - libswresample-dev libswscale-dev libavcodec-dev libavformat-dev libavresample-dev
            - libglib2.0-dev
            - unzip
            - libjson-c-dev intltool pkg-config
            - # for gperftools
            - autoconf automake libtool libunwind-dev
            - # skia dependencies
            - build-essential freeglut3-dev libfontconfig-dev libfreetype6-dev
            - libgif-dev libgl1-mesa-dev libglu1-mesa-dev libharfbuzz-dev
            - libicu-dev libjpeg-dev libpng-dev libwebp-dev
            - p7zip-full libpulse-dev libxkbcommon-x11-0 libgstreamer-plugins-base1.0-0
            - libgtk2.0-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - QT_INSTALL_DIR=~/Qt
        - QT_VERSION=5.12.4
        - QT_CONTENT=${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64
        - QT_BIN=${QT_CONTENT}/bin
        - PATH="${QT_BIN}:${PATH}"
        - QT_LIB=${QT_CONTENT}/lib
        - LD_LIBRARY_PATH="${QT_LIB}:${LD_LIBRARY_PATH}"
        - TRAVIS_CACHE_DIR=$TRAVIS_BUILD_DIR/cache
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      addons:
        homebrew:
          packages:
            - zlib
            - json-c
            - intltool
            - pkg-config
            - gettext
            - ffmpeg
            - p7zip
            - wget
            - curl
            - libomp
            - grep
          update: true
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - QT_INSTALL_DIR=~/Qt
        - QT_VERSION=5.12.4
        - QT_CONTENT=${QT_INSTALL_DIR}/${QT_VERSION}/clang_64
        - QT_BIN=${QT_CONTENT}/bin
        - PATH="${QT_BIN}:${PATH}"
        - QT_LIB=${QT_CONTENT}/lib
        - LD_LIBRARY_PATH="${QT_LIB}:${LD_LIBRARY_PATH}"
        - TRAVIS_CACHE_DIR=$TRAVIS_BUILD_DIR/cache_osx
cache:
    directories:
        - $TRAVIS_CACHE_DIR
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          chmod +x .travis_linux_install.sh
          ./.travis_linux_install.sh
      elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
          chmod +x .travis_osx_install.sh
          ./.travis_osx_install.sh
      fi
script:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          chmod +x .travis_linux_script.sh
          ./.travis_linux_script.sh
      elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
          chmod +x .travis_osx_script.sh
          ./.travis_osx_script.sh
      fi
after_success:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          chmod +x .travis_linux_success.sh
          ./.travis_linux_success.sh
      elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
          chmod +x .travis_osx_success.sh
          ./.travis_osx_success.sh
      fi
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
